### ISSUE TITLE
Support for (unsafe) atomic numeric and bit operations

### ISSUE THREAD

**Issue by eggyal** [taiki-e/atomic-maybe-uninit#23]
Another fantastically useful concurrency crate—thank you, @taiki-e !

I'm using `atomic-maybe-uninit` to workaround rust-lang/unsafe-code-guidelines#517.  In particular, I transmute between "tagged pointer" structs similar to the following and `MaybeUninit<u128>` in order to manipulate atomically in an `AtomicMaybeUninit<u128>` without loss of pointer provenance:

```rust
#[cfg(target_pointer_width = "64")]
#[repr(C)]
pub struct TaggedPtr<T> {
    _align: [u128; 0],

    #[cfg(target_endian = "little")]
    pub tag: usize,

    pub ptr: *mut T,

    #[cfg(target_endian = "big")]
    pub tag: usize,
}
```

There are times that I need to atomically add/subtract from the `tag`.  Currently, I do this via `fetch_update`—however that is obviously suboptimal, as it produces a compare-exchange loop.  I'd *like* instead to be able to do a `fetch_add`/`fetch_sub` (and, by extension, one can also imagine cases where the other atomic bit and numeric operations might also be desirable).<sup>1</sup>

Clearly such operations must be `unsafe` as the caller must guarantee that the value has been fully initialised.  Indeed, casting as a fully initialised atomic, eg `AtomicU128`, to perform the operation is a possibility; but any value returned from such functions would then have lost pointer provenance, necessitating a subsequent load from the (uncasted) `AtomicMaybeUninit` to regain provenance—and thereby opening the door for other threads to modify the value in the interim.

Would you be open to adding such `unsafe` operations to `AtomicMaybeUninit`?

---

<sub>1. Before transmuting back from such a manipulated `MaybeUninit<integer>`, one must obviously check that the data is valid for the destination type; in this case, I will have to check that the `tag` did not overflow.</sub>

**Comment by RalfJung** [comment]
So what you are looking for are provenance-preserving fetch_add/sub? As in, atomic pointer arithmetic?

**Comment by eggyal** [comment]
These operations won't actually modify the pointer, but yes I suppose the compiler will have to assume that it's pointer arithmetic.

**Comment by taiki-e** [comment]
As for fetch_add/fetch_sub, since double-wide atomic add/subtract instructions are not available in any architecture, I don't feel that this API is particularly efficient compared to the CAS loop (aside from LL/SC. well LLVM [uses CAS instructions when it is available instead of LL/SC instructions](https://github.com/llvm/llvm-project/commit/10d34f5538e0d231a172608bdb7d08824771c7c7), although). For 128-bit atomic instructions see this [table](https://github.com/taiki-e/portable-atomic/tree/main/src/imp/atomic128#128-bit-atomics-instructions).

As for bit operations, I have previously written implementations for aarch64: https://github.com/taiki-e/atomic-maybe-uninit/tree/rmw
Also, in my understanding, perhaps there would be no need for safety requirements on initialization at the AtomicMaybeUninit API level (`iiuu <op> iuiu == iuuu` (i=init,u=uninit) should be able to guarantee).
That said, there should be very few (perhaps none at all in practice) CPUs at this time that actually support double-width atomic bit operation instructions as well (see the table mentioned above).

**Comment by RalfJung** [comment]
> AtomicMaybeUninit API level (iiuu <bit-op> iuiu == iuuu (i=init,u=uninit) should be able to guarantee).

I'm not sure what you mean, but bit operations on uninit data are *UB*. Rust doesn't have "poison" semantics, it has "immediate UB" semantics for operations like this.

**Comment by taiki-e** [comment]
@RalfJung 

> I'm not sure what you mean, but bit operations on uninit data are UB. Rust doesn't have "poison" semantics, it has "immediate UB" semantics for operations like this.

It was over a year ago, so I don't remember exactly what happened, but I think I was thinking about what actually happens with bit operations on the assembly (hardware) side and how much of that could be reflected in the API.

**Comment by taiki-e** [comment]
In any case, for such a use case (all initialized), I think it would be better to add something like AtomicDoublePtr to portable-atomic crate, where the necessary implementation is already almost there, than to add such an API to this crate.

**Comment by eggyal** [comment]
> As for fetch_add/fetch_sub, since double-width atomic add/subtract instructions are not available in any architecture

Ah, this I hadn't realised.   The paper I was reading relies on double-width atomic RMW (read-modify-write) ops, and in pseudocode details an algorithm applying FAA (fetch-and-add) to a double-width variable, which is why I was searching for such facility so that I could play with an implementation in Rust.  Looking now at the reference C++ implementation, I see that it calls gcc libatomic's [`atomic_fetch_add`](https://en.cppreference.com/w/c/atomic/atomic_fetch_add) which indeed compiles to a CAS loop if the architecture lacks native support ([godbolt](https://godbolt.org/z/b41xcszvY)), which hadn't been clear to me from its documentation.

Therefore I personally no longer have a use for this and am quite happy for the issue to be closed.

Thank you all for indulging me with your time and consideration; apologies for my misunderstanding.
